version: '3.8'
networks:
  pdk:
    driver: bridge
services:
  ideate: #in container-based development
    # image: pilotcity/boiler
    container_name: ideate
    build: .
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - MEMORY_LIMIT=2048
      - MAX_THREADS=4
      - npm_config_unsafe_perm=true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8006:8080
    stdin_open: true
    tty: true
    command: ["yarn","run","serve"]
    networks: 
      - pdk
